<?php
require_once __DIR__ . '/data/products.php';
$id = isset($_GET['id']) ? (int) $_GET['id'] : 1;
$product = $products[$id] ?? reset($products);
$related = array_slice(array_filter($products, fn($item) => $item['id'] !== $product['id']), 0, 4, true);
include __DIR__ . '/includes/header.php';
?>
<main class="detail-page"><div class="container"><section class="detail-grid section-space"><div class="gallery-wrap"><div class="thumb-list"><?php foreach ($product['gallery'] as $index => $image): ?><button class="thumb-btn <?php echo $index === 0 ? 'active' : ''; ?>" type="button" data-target="<?php echo htmlspecialchars($image); ?>"><img src="<?php echo $image; ?>" alt="Thumbnail <?php echo $index + 1; ?>"></button><?php endforeach; ?></div><div class="main-preview"><img id="mainProductImage" src="<?php echo $product['image']; ?>" alt="<?php echo htmlspecialchars($product['name']); ?>"></div></div><div class="detail-info"><h1><?php echo htmlspecialchars($product['name']); ?></h1><div class="rating-row"><span class="stars"><?php echo str_repeat('★', (int)$product['rating']); ?><?php echo str_repeat('☆', 5 - (int)$product['rating']); ?></span><span>(<?php echo (int)$product['reviews']; ?> Reviews)</span><span class="stock-tag"><?php echo htmlspecialchars($product['stock']); ?></span></div><div class="detail-price"><?php echo number_format($product['price'], 0, ',', '.'); ?>đ</div><p class="detail-desc"><?php echo htmlspecialchars($product['description']); ?></p><ul class="product-specs"><li><strong>Studio:</strong> <?php echo htmlspecialchars($product['studio']); ?></li><li><strong>Kích thước:</strong> <?php echo htmlspecialchars($product['size']); ?></li><li><strong>SKU:</strong> <?php echo htmlspecialchars($product['sku']); ?></li></ul><div class="purchase-box"><div class="quantity-box"><button type="button" class="qty-btn" data-qty="minus">−</button><input type="text" value="1" id="qtyInput" readonly><button type="button" class="qty-btn plus" data-qty="plus">+</button></div><a href="#" class="primary-btn buy-btn">Buy Now</a><button class="wishlist-btn" type="button">♡</button></div><div class="feature-box"><div class="feature-item"><div class="feature-icon">🚚</div><div><h4>Free Delivery</h4><p>Enter your postal code for delivery availability</p></div></div><div class="feature-item"><div class="feature-icon">↩</div><div><h4>Return Delivery</h4><p>Free 30 days delivery returns. Details</p></div></div></div></div></section><section class="section-space"><div class="section-label">Related Item</div><div class="product-grid"><?php foreach ($related as $item): ?><article class="product-card"><a href="product-detail.php?id=<?php echo $item['id']; ?>" class="product-image"><img src="<?php echo $item['image']; ?>" alt="<?php echo htmlspecialchars($item['name']); ?>"><span class="badge-ribbon">New</span></a><div class="product-meta"><div class="studio"><?php echo htmlspecialchars($item['studio']); ?></div><h3><a href="product-detail.php?id=<?php echo $item['id']; ?>"><?php echo htmlspecialchars($item['name']); ?></a></h3><div class="price-line"><strong><?php echo number_format($item['price'], 0, ',', '.'); ?>đ</strong></div></div></article><?php endforeach; ?></div></section></div></main>
<?php include __DIR__ . '/includes/footer.php'; ?>
